### ISSUE TITLE
Make the Proxy capable to auto-restart parent server

### ISSUE THREAD

**Issue by mauzao9** [StarryPy/StarryPy#107]
Heya.

I believe that like Starrybound the wrapper should be capable to deal with common issues with the parent server software, as crashes, and "freezes" where server is running but non-responding, the wrapper should ping the parent server and be able to start it if not running, and restart it if something is not right.

**Comment by kamilion** [comment]
This feature is already available in the web_gui plugin.

```json
        "web_gui": {
            "cookie_token": "HERPDERP",
            "log_path": "webgui.log",
            "log_path_access": "webgui_access.log",
            "ownerpassword": "DAPASSWORD",
            "port": 8083,
            "remember_cookie_token": true,
            "restart_script": "restartsb"
        }
```

And here is the content of my /usr/local/bin/restartsb script:
```bash
#!/bin/bash
killall -u starbound -s SIGQUIT -w starbound_server
```

Closing #107.
