### ISSUE TITLE
Variant has no _build function

### ISSUE THREAD

**Issue by athalean** [StarryPy/StarryPy#114]
in [/packets/data_types.py](https://github.com/CarrotsAreMediocre/StarryPy/blob/master/packets/data_types.py#L99)

`Variant` class lacks a `_build` method. Some build functions like `client_connect().build(...)` raise `NotImplementedError` because of this.

**Comment by kamilion** [comment]
If this issue is still present in StarryPy 1.7 for protocol 691, please reopen this issue.
Closing #114.
