### ISSUE TITLE
Planet Protect Projectiles

### ISSUE THREAD

**Issue by Tsunder** [StarryPy/StarryPy#117]
Planetary protect would ideally stop players off the whitelist from having projectiles.

With the surge of players who have reached endgame and have decided for some reason to wander into modding, many are finding workarounds to a projectile blacklist.
So long as there exists one projectile that a griefer can use, they can do as much harm as they can with any projectile.
I promote one preferred solution and one alternate solutions: 
-) To allow only builders in the protect list to freely spawn projectiles
alternate:
--) To intercept the projectile configuration packet and to clean that.

Also, create monster and NPC should be checked too.

**Comment by kamilion** [comment]
Hm, not sure if any work was done on this issue; please check StarryPy 1.7 for protocol 691 and see if the issue remains. If so, feel free to reopen this issue, or create a new one. Closed #117.
