### ISSUE TITLE
Using cyrillic names

### ISSUE THREAD

**Issue by deranon** [StarryPy/StarryPy#121]
When someone use cyrillic (and maybe other non-latin) symbols in name, all StarryPy plugins ignore player.He cant use commands, but he can bypass protection (!) and cause many lags and error spam in console.

**Comment by kamilion** [comment]
Try starrypy3k instead. Python 2.x isn't great with unicode.

That said, the source of many players escaping protection (faulty clone-detection code) has recently been fixed to a degree.

Closing #121.
