### ISSUE TITLE
StarryPy doenst work with unstable build

### ISSUE THREAD

**Issue by RogerSik** [StarryPy/StarryPy#122]
Hello,

i wanted to use StarryPy now for the unstable build.

But when i start StarryPy this message appear:
CRITICAL - A plugin reported a fatal error. Error: Could not open starbound configuration file. Tried path: FilePath(u'/home/game-srv/programs/steam/SteamApps/common/Starbound-unstable/starbound.config')

The configuration file has in unstablea another name  (starbound_server.config) and it can be found in the folder storage_unstable.

Greetings
Roger

**Comment by teihoo** [comment]
kharidiron has been working on packet modification for nightly/unstable build. https://github.com/kharidiron/StarryPy/tree/development I'll try to bring this to the master branch here. As kharidiron says, some stuff is still not working properly (like warping), so we'll try to fix that before making a pull.

**Comment by kamilion** [comment]
All known packets in MASTER are up to date as of the unstable build of protocol 691.
Closing #122.
