### ISSUE TITLE
Can't find starbound.config

### ISSUE THREAD

**Issue by Jintezaku** [StarryPy/StarryPy#136]
Starbound.config is located in the giraffe_data folder since the latest stable build. StarryPy was giving me an error that it couldn't find the starbound.config in the main data folder. So I added starbound_config path to StarryPy's config.json and changed the configuration_file var accordingly in the starbound_config_manager, everything seems to be working now.

**Comment by kharidiron** [comment]
If you updated the line in config.json to be:
```"starbound_path": "/home/starbound/Starbound/giraffe_storage",```
or wherever you happen to have your giraffe_storage folder, it would have the same effect. No need for adding variables, etc..

I should rename that variable to make it clearer. (It is a legacy name from when koala stored the starbound.config in the top level directory).

**Comment by kamilion** [comment]
I'm calling this issue "User Error" then. Pop a new issue if you want to submit a PR, otherwise, Closing #136.
