### ISSUE TITLE
Issue in plugin_manager.py/resolve_dependencies

### ISSUE THREAD

**Issue by moebiuz** [StarryPy/StarryPy#143]
Hi.

Server is not loading plugins due to dependency problems. Seems resolve_dependencies() is not working well,  I managed to temporally fix it changing

if ready:

with

if ready = []:

and now works correctly. I don't do a push request, perhaps yo have a better solution.

Also you should document a bit better config.json (or change implementation), since by default starbound.config is in starbound/giraffe_storage, and not in starbound root folder (where starrypy is looking for). Perhaps "starboundconfig_path" is better than "starbound_path".

Cheers

**Comment by 8r2y5** [comment]
it should be if not ready: and it will work

**Comment by 8r2y5** [comment]
cant edit comment via phone, that changes that made thad bug are reverted, issue should be closed

**Comment by kharidiron** [comment]
Old issue is old. closing.
