### ISSUE TITLE
Error when starting server

### ISSUE THREAD

**Issue by Dernert** [StarryPy/StarryPy#170]
When i type
"python server.py"

> :0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
> Traceback (most recent call last):
>   File "server.py", line 30, in <module>
>     from packets import Packets, Direction, chat_received
>   File "/home/starrypy/StarryPy/packets/__init__.py", line 1, in <module>
>     from data_types import *
>   File "/home/starrypy/StarryPy/packets/data_types.py", line 3, in <module>
>     from construct import (
> ImportError: cannot import name BFloat32

Any ideas? :D

**Comment by Dernert** [comment]
Solved

**Comment by kindaworking** [comment]
How did you solve this? Running into the same issue.

**Comment by AMorporkian** [comment]
You should be able to do `pip install service_identity`.
