### ISSUE TITLE
StarryPy doesnt start

### ISSUE THREAD

**Issue by ashk0re** [StarryPy/StarryPy#171]
I followed all installtion steps and installed all requirements. Starbound server is running.

Error:

Traceback (most recent call last):
  File "server.py", line 30, in <module>
    from packets import Packets, Direction, chat_received
  File "/opt/StarryPy/packets/__init__.py", line 1, in <module>
    from data_types import *
  File "/opt/StarryPy/packets/data_types.py", line 3, in <module>
    from construct import (
ImportError: cannot import name BFloat32

Please help me. Thanks

**Comment by medeor413** [comment]
As of Starbound 1.0, StarryPy is deprecated. Please switch your server to use [StarryPy3k](https://github.com/StarryPy/StarryPy3k), a rewritten version of StarryPy with 1.0 support.
