### ISSUE TITLE
sophisticated rights management 

### ISSUE THREAD

**Issue by MrMarvin** [StarryPy/StarryPy#47]
We had a discussion on sbreddit what a proper rights management for protected planets should look like.
Suggestions were:
- unregistered users should be able to pick up dropped items, easy fix: allow REQUEST_DROP packets
-  unregistered users should be able to use doors, chairs and such which basically is allowing the ENTITY_INTERACT packets trough. 
-- Problem here is that users now can interact with chests and the like but OPEN_CONTAINER is blocked. As a result the client hangs with an open but empty chest window and can not be closed properly. To prevent that, allowing OPEN_CONTAINER will result in the client being able to see the container, but still WILL HANG when it tries to move things in it.
Further research is needed here, whether or not its feasible to intercept and answer the client with fake packets rather than simply block it altogether.

I suspect this to be part of a larger rewrite of a role based permissions system.

**Comment by kamilion** [comment]
Comments acknowledged.
If this issue is still important, please re-open it or create a new issue.

Closing #47.
