### ISSUE TITLE
Clients disconnected when issuing /help

### ISSUE THREAD

**Issue by jedinerd** [StarryPy/StarryPy#72]
After updating the most recent master clients are being disconnected when issuing /help

Warn: Perf: UniverseServer::run.innerloop millis: 1558
Warn: I/O error from 127.0.0.1:55127 in NetSocket read loop or device closed: EofException: Error, unexpected end of file found 97 3 3
./linux64/starbound_server(_ZN4Star13StarExceptionC2ERKSs+0xfe) [0xdc4ece]
./linux64/starbound_server(_ZN4Star6Buffer4readEPcm+0xef) [0xd2adaf]
./linux64/starbound_server(_ZN4Star10DataStream8readDataEPcm+0x1e) [0xd35c4e]
./linux64/starbound_server(_ZN4Star10DataStream14readStringDataERNS_9ByteArrayE+0xa8) [0xd362b8]
./linux64/starbound_server(_ZN4Star10DataStreamrsERNS_6StringE+0x26) [0xd362f6]
./linux64/starbound_server(_ZN4Star9NetSocket10readerLoopEv+0x17e) [0xa6d2ee]
./linux64/starbound_server(_ZN4Star10ThreadImpl9runThreadEPv+0x21) [0xdcb5d1]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7e9a) [0x7f062ca96e9a]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f062bdad3fd]

**Comment by kamilion** [comment]
This issue is a year and a half out of date, with no further information provided by the original poster.
If you can reproduce the issue in Starrypy 1.7 for protocol 691 or higher, please reopen the issue or open a new issue. Closing #72.
