### ISSUE TITLE
Using /promote with multiple same named characters, promotes only first one

### ISSUE THREAD

**Issue by teihoo** [StarryPy/StarryPy#86]
I've been testing some race mod and I created a buch of same named chars. They all have unique ID, then i wanted to promote the last one to admin, and nothing happened. Checking the database showed, it added 100 to the first character with that name.

**Comment by kamilion** [comment]
Known issue, but we're through with trying to prevent duplicate players... it causes more trouble than it's worth. Instead, you can use the web_gui and change the correct player's rank there.
Closed #86, please reopen or create a new issue.
